QUARTER_DURATION_SECONDS = 720
CLIP_PRE_ROLL_SECONDS = 7
CLIP_POST_ROLL_SECONDS = 1
CLIP_TOTAL_SECONDS = 8
SHORT_MAX_DURATION_SECONDS = 120
MINIMUM_IMPORTANCE_SCORE = 70
FRAME_SAMPLE_INTERVAL_SECONDS = 30
NBA_QUARTERS = [1, 2, 3, 4]
OVERTIME_DURATION_SECONDS = 300

# Limits clips per player; raised to 20 for full-game reels
MAX_CLIPS_PER_PLAYER = 20

# Phase 5A: Self-correcting anchor chain constants
REFINEMENT_WINDOW_SECONDS = 45
QUARTER_BREAK_SEARCH_SECONDS = 300
DEGRADED_WINDOW_MULTIPLIER = 3
DEAD_BALL_RATIO = 1.6
