QUARTER_DURATION_SECONDS = 720
CLIP_PRE_ROLL_SECONDS = 8
CLIP_POST_ROLL_SECONDS = 12
SHORT_MAX_DURATION_SECONDS = 120
MINIMUM_IMPORTANCE_SCORE = 70
FRAME_SAMPLE_INTERVAL_SECONDS = 30
NBA_QUARTERS = [1, 2, 3, 4]
OVERTIME_DURATION_SECONDS = 300

# Limits clips per player to keep demo fast and focused
# Clips are selected by highest importance_score first
MAX_CLIPS_PER_PLAYER = 5
